Issue/#12
ninadarbaidze/movie-quotes-front-ninadarbaidze pull request #20
Opened 2022-09-06 16:47 UTC by ninadarbaidze

closes #12

2022-09-06 16:50 UTC, GigaGiorgadze requested changes

2022-09-06 16:50 UTC, GigaGiorgadze commented on public/locales/en/movies.json
> +{"addbtn":"Add movie","addMovie":"Add movie","budget":"Budget","changeImg":"Change photo","chooseFile":"Choose file","descriptionH1":"Movie Description","director":"Director","drag":"Drag & drop your
format.... every file

2022-09-06 16:50 UTC, GigaGiorgadze commented on schema/quoteSchema.ts
> +      .matches(/[\u10A0-\u10FF]/, 'წერე ქართულად'),
why is this a hook? just pass home:commondRequired as ke and then use it in file, just overcomplicating

2022-09-06 16:59 UTC, ninadarbaidze commented on schema/quoteSchema.ts
> +      .matches(/[\u10A0-\u10FF]/, 'წერე ქართულად'),
I can't use t without react component, or you're saying something else?

2022-09-07 06:44 UTC, GigaGiorgadze commented on schema/quoteSchema.ts
> +      .matches(/[\u10A0-\u10FF]/, 'წერე ქართულად'),
ik that what im saying just type required(home:commandRequired) and then translate it in component when error happens not here

2022-09-07 07:36 UTC, ninadarbaidze commented on schema/quoteSchema.ts
> +      .matches(/[\u10A0-\u10FF]/, 'წერე ქართულად'),
oh I get it now

2022-09-07 08:16 UTC, GigaGiorgadze approved these changes

2022-09-07 08:16 UTC, merged