Feat/profile
ninadarbaidze/movie-quotes-front-ninadarbaidze pull request #5
Opened 2022-08-10 13:26 UTC by ninadarbaidze

2022-08-10 13:41 UTC, GigaGiorgadze requested changes

2022-08-10 13:41 UTC, GigaGiorgadze commented on components/Profile/EditProfile/types.d.ts
> +  userData: any;
no any >:(

2022-08-10 13:41 UTC, GigaGiorgadze commented on components/Profile/EditProfile/types.d.ts
> +  userData: any;
do u have good reason for any?

2022-08-10 13:41 UTC, GigaGiorgadze commented on components/Profile/ProfileForm/ProfileForm.tsx
> +  const changeHandler = (e: any) => {
no any this is ChangeEvent<HTMLInputElement>

2022-08-10 13:41 UTC, GigaGiorgadze commented on components/Profile/ProfileForm/ProfileForm.tsx
> +  const fileRef = useRef<HTMLInputElement>(null);
move this stuff inside custom hook, not just here but everywhere, this file should have only custom hook and jsx nothing else

2022-08-10 13:41 UTC, GigaGiorgadze commented on components/Profile/ProfileForm/useProfileForm.ts
> +  const onSubmit = async (values: any) => {
no any

2022-08-10 13:41 UTC, GigaGiorgadze commented on components/Profile/ProfileForm/useProfileForm.ts
> +    formData.append('password', values.password);
why not just loop over vlues

2022-08-10 13:41 UTC, GigaGiorgadze commented on components/Profile/SideBar/SideBar.tsx
> +      return `${process.env.NEXT_PUBLIC_API_URL}/${userCtx.userState.profileImage}`;
also move this inside custom hook, and as i said before everywhere else,

2022-08-10 13:41 UTC, GigaGiorgadze commented on pages/feed/profile/index.tsx
> +    console.log(ctx.isLoggedIn);
remove console log

2022-08-10 13:41 UTC, GigaGiorgadze commented on services/profileRequests.ts
> +): Promise<AxiosResponse<any>> => {
give this return type, first can be any cuz its error if i remember but second parameter should be return type

2022-08-10 13:41 UTC, GigaGiorgadze commented on store/AuthContext.tsx
> +  const [token, setToken] = useState(initialToken) as any;
no any

2022-08-10 13:41 UTC, GigaGiorgadze commented on store/UserContext.tsx
> +    dispatchUserAction({
why u need this context? don't u have next auth useSession?

2022-08-10 15:23 UTC, ninadarbaidze commented on store/UserContext.tsx
> +    dispatchUserAction({
I'm storing user-related data here, planning to add movies related context and that's it. can I keep it here? authcontext is leaner this way

2022-08-10 16:42 UTC, GigaGiorgadze commented on store/UserContext.tsx
> +    dispatchUserAction({
may i ask why u need authContext?

2022-08-11 07:03 UTC, GigaGiorgadze requested changes

2022-08-11 07:03 UTC, GigaGiorgadze commented on components/Profile/SideBar/helper.ts
> +  session: any
why is sessionAny? is this next-auth session? if so I think that has type Session

2022-08-11 07:39 UTC, GigaGiorgadze approved these changes

2022-08-11 07:39 UTC, merged